'use client'
import { useState } from 'react'
import { useAuthReady } from '@/hooks/useAuthReady'
import { apiFetch } from '@/lib/apiClient'
const sample = { contract: 'ecla.rubric/1', targetKey: 'gateway:stranger_intro', claim: 'text_functional', criteria: [{ id: 'greeting', description: 'Learner greets the partner', matchAny: ['hola', 'buenas'], required: true }], minLearnerTurns: 2, requiresRepair: false, calibration: { sampleSize: 0, agreement: 0, population: 'No calibration study recorded' } }
type SessionReview = { results: { id: string; scenarioId: string; humanDecision: boolean | null }[]; acoustics: { id: string; scenarioId: string }[]; audits: { id: string; action: string; actor: string }[] }
export default function AssessmentAdminPage() {
    const { getToken } = useAuthReady()
    const [source, setSource] = useState(JSON.stringify(sample, null, 2)); const [rubrics, setRubrics] = useState<{ id: string; targetKey: string; version: string; status: string }[]>([])
    const [note, setNote] = useState(''); const [sessionId, setSessionId] = useState(''); const [session, setSession] = useState<SessionReview | null>(null); const [message, setMessage] = useState<string | null>(null)
    const [providerReference, setProviderReference] = useState(''); const [providerVersion, setProviderVersion] = useState(''); const [confidence, setConfidence] = useState('0.80'); const [intelligibility, setIntelligibility] = useState('0.80'); const [consent, setConsent] = useState(false)
    const request = <T,>(path: string, body?: unknown) => apiFetch<T>(path, getToken, body === undefined ? undefined : { method: 'POST', body: JSON.stringify(body) })
    const loadRubrics = async () => setRubrics((await request<{ rubrics: typeof rubrics }>('/api/v1/admin/assessment-rubrics')).rubrics)
    const loadSession = async () => setSession(await request(`/api/v1/admin/assessment-sessions/${encodeURIComponent(sessionId)}`))
    const run = async (work: () => Promise<void>) => { setMessage(null); try { await work() } catch (error) { setMessage(error instanceof Error ? error.message : 'Request failed') } }
    const button = 'rounded-xl border border-white/20 px-4 py-2 disabled:opacity-40'
    const attach = (scenarioId: string) => run(async () => { await request(`/api/v1/admin/assessment-sessions/${sessionId}/acoustic-observations`, { scenarioId, providerReference, providerVersion, metrics: { intelligibility: Number(intelligibility) }, confidence: Number(confidence), consentAttested: consent, note }); await loadSession() })
    const decide = (result: SessionReview['results'][number], approved: boolean) => run(async () => { const acoustic = session?.acoustics.find(item => item.scenarioId === result.scenarioId); await request(`/api/v1/admin/assessment-results/${result.id}/review`, { approved, expectedDecision: result.humanDecision, confidence: Number(confidence), intelligibility: approved ? Number(intelligibility) : null, acousticObservationId: approved ? acoustic?.id ?? null : null, note }); await loadSession() })
    return <main className="min-h-screen bg-[#0B0B10] p-6 text-cream"><div className="mx-auto max-w-5xl space-y-6"><a href="/admin">Back to admin</a><h1 className="text-3xl font-bold">Assessment review</h1><p>API admin authorization is mandatory. Calibration metadata must come from a real study. Spoken approval requires a consented external acoustic observation; this page stores a provider reference and metrics, never raw audio.</p>{message && <p role="status">{message}</p>}
        <label className="block">Rubric JSON<textarea className="mt-2 h-80 w-full rounded-xl bg-black/30 p-4 font-mono" value={source} onChange={event => setSource(event.target.value)} /></label><button className={button} onClick={() => run(async () => { await request('/api/v1/admin/assessment-rubrics', JSON.parse(source)); await loadRubrics() })}>Save immutable rubric draft</button><button className={button} onClick={() => run(loadRubrics)}>Load rubrics</button>
        <label className="block">Review note<input className="mt-2 w-full rounded-xl bg-black/30 p-3" value={note} minLength={20} onChange={event => setNote(event.target.value)} /></label>{rubrics.map(row => <div key={row.id} className="rounded-xl border p-4"><p>{row.targetKey} · {row.status}</p><p className="break-all text-xs">{row.version}</p><button className={button} disabled={row.status === 'reviewed' || note.length < 20} onClick={() => run(async () => { await request(`/api/v1/admin/assessment-rubrics/${row.id}/review`, { note }); await loadRubrics() })}>Attest review and calibration</button></div>)}
        <h2 className="text-2xl font-bold">Session evidence review</h2><label>Session UUID<input className="ml-2 rounded-xl bg-black/30 p-3" value={sessionId} onChange={event => setSessionId(event.target.value)} /></label><button className={button} onClick={() => run(loadSession)}>Load server transcript and audit</button>
        {session && <div className="grid gap-3 sm:grid-cols-2"><label>Provider reference<input className="block w-full rounded-xl bg-black/30 p-3" value={providerReference} onChange={event => setProviderReference(event.target.value)} /></label><label>Provider/version<input className="block w-full rounded-xl bg-black/30 p-3" value={providerVersion} onChange={event => setProviderVersion(event.target.value)} /></label><label>Confidence 0–1<input className="block w-full rounded-xl bg-black/30 p-3" value={confidence} onChange={event => setConfidence(event.target.value)} /></label><label>Intelligibility 0–1<input className="block w-full rounded-xl bg-black/30 p-3" value={intelligibility} onChange={event => setIntelligibility(event.target.value)} /></label><label className="flex gap-2"><input type="checkbox" checked={consent} onChange={event => setConsent(event.target.checked)} />I verified recording consent and the provider reference.</label></div>}
        {session?.results.map(result => { const acoustic = session.acoustics.find(item => item.scenarioId === result.scenarioId); return <div key={result.id} className="space-y-3 rounded-xl border p-4"><p>{result.scenarioId} · decision {String(result.humanDecision)} · acoustic {acoustic ? acoustic.id : 'missing'}</p><button className={button} disabled={!consent || note.length < 20 || !providerReference || !providerVersion} onClick={() => attach(result.scenarioId)}>Attach reviewed acoustic observation</button><button className={button} disabled={!acoustic || note.length < 20} onClick={() => decide(result, true)}>Approve with acoustic evidence</button><button className={button} disabled={note.length < 20} onClick={() => decide(result, false)}>Do not approve</button></div> })}
        {session && <details><summary>Audit history</summary>{session.audits.map(item => <p key={item.id}>{item.action} · {item.actor}</p>)}</details>}
    </div></main>
}
