export type AddedCompetencySeed = {
    unit: number; code: string; title: string; canDo: string; domain: string
    patterns: string[]; examples: string[]; prerequisites: string[]
    vocabulary: Array<{ word: string; translation: string; importance?: number }>
    pronunciationNote?: string; culturalNote?: string
}

export const PRE_A1_ADDED_COMPETENCIES: readonly AddedCompetencySeed[] = [
    { unit:1, code:'PA1.SND.PRD.01', title:'Produce familiar words intelligibly', canDo:'Produce familiar Spanish words and chunks clearly enough to be understood.', domain:'SOUND', patterns:['Hola.','Gracias.','Agua, por favor.'], examples:['Hola.','Gracias.','Agua, por favor.'], prerequisites:[], vocabulary:[], pronunciationNote:'Intelligibility is judged from actual audio in context; transcription confidence is never pronunciation evidence.' },
    { unit:1, code:'PA1.SND.WRD.01', title:'Hear familiar word boundaries and stress', canDo:'Locate a familiar word or chunk in short, supported speech.', domain:'SOUND', patterns:['GRA-cias','bue-NOS DÍ-as','por fa-VOR'], examples:['Gracias.','Buenos días.','Por favor.'], prerequisites:[], vocabulary:[], pronunciationNote:'Use independently reviewed audio models. The stress model for gracias is GRA-cias.' },
    { unit:1, code:'PA1.RDG.DEC.01', title:'Connect written and spoken forms', canDo:'Connect familiar written words and digits with what is heard.', domain:'READING', patterns:['hola ↔ Hola','dos ↔ 2','gracias ↔ Gracias'], examples:['Hola','Gracias','2'], prerequisites:[], vocabulary:[] },
    { unit:3, code:'PA1.WRT.INF.01', title:'Enter simple personal information', canDo:'Complete a short form using safe real or fictional personal details.', domain:'WRITING', patterns:['Nombre: + nombre','Ciudad: + ciudad','Idiomas: + idioma'], examples:['Nombre: Ana','Ciudad: Lima','Idiomas: español e inglés'], prerequisites:[], vocabulary:[{word:'nombre',translation:'name'},{word:'ciudad',translation:'city'},{word:'idioma',translation:'language'}], culturalNote:'Learners may use fictional data and should never be required to disclose an exact address.' },
    { unit:3, code:'PA1.WRT.MSG.01', title:'Write a short practical message', canDo:'Write a very short message with a greeting and one practical detail or request.', domain:'WRITING', patterns:['Hola, + detalle.','Hola, necesito + cosa.','Nos vemos + tiempo.'], examples:['Hola, necesito ayuda.','Hola, nos vemos mañana.'], prerequisites:[], vocabulary:[{word:'mensaje',translation:'message'}] },
    { unit:3, code:'PA1.PER.ROL.01', title:'State a chosen role', canDo:'State a chosen familiar role without compulsory employment disclosure.', domain:'PERSONAL', patterns:['Soy estudiante.','Soy profesor/profesora.','Trabajo en + lugar.'], examples:['Soy estudiante.','Trabajo en una tienda.'], prerequisites:[], vocabulary:[{word:'estudiante',translation:'student'},{word:'profesor',translation:'teacher'},{word:'tienda',translation:'shop'}], culturalNote:'Role and employment information are optional; fictional roles are valid.' },
    { unit:4, code:'PA1.RDG.SGN.01', title:'Interpret familiar signs and labels', canDo:'Choose an appropriate action from a familiar sign, label, or menu item.', domain:'READING', patterns:['Entrada','Salida','Abierto','Cerrado'], examples:['Entrada','Salida','Cerrado'], prerequisites:['PA1.RDG.DEC.01'], vocabulary:[{word:'entrada',translation:'entrance'},{word:'salida',translation:'exit'},{word:'abierto',translation:'open'},{word:'cerrado',translation:'closed'}] },
    { unit:4, code:'PA1.WLD.POS.01', title:'Express basic possession', canDo:'State, ask, and confirm who a familiar object belongs to.', domain:'WORLD', patterns:['Es mi + objeto.','¿Es tu + objeto?','Sí, es mío/mía.'], examples:['Es mi libro.','¿Es tu bolsa?','Sí, es mía.'], prerequisites:['PA1.WLD.OBJ.01'], vocabulary:[{word:'mi',translation:'my'},{word:'tu',translation:'your'},{word:'libro',translation:'book'}] },
    { unit:4, code:'PA1.WLD.EXT.01', title:'State presence or absence', canDo:'State whether a familiar item or place is present or available.', domain:'WORLD', patterns:['Hay + objeto.','No hay + objeto.','¿Hay + lugar?'], examples:['Hay agua.','No hay café.','¿Hay un baño?'], prerequisites:['PA1.WLD.OBJ.01'], vocabulary:[{word:'hay',translation:'there is / there are'},{word:'no hay',translation:'there is not / there are not'}] },
    { unit:5, code:'PA1.ACT.RTN.01', title:'State a familiar action or routine', canDo:'State one or two familiar actions using reviewed chunks.', domain:'ACTION', patterns:['Estudio.','Trabajo aquí.','Como a las doce.'], examples:['Estudio.','Trabajo aquí.'], prerequisites:[], vocabulary:[{word:'estudio',translation:'I study'},{word:'trabajo',translation:'I work'},{word:'aquí',translation:'here'}] },
    { unit:5, code:'PA1.NED.ABL.01', title:'Express ability or inability', canDo:'State whether you can do one familiar action.', domain:'NEEDS', patterns:['Puedo + acción.','No puedo + acción.'], examples:['Puedo ayudar.','No puedo ir.'], prerequisites:[], vocabulary:[{word:'puedo',translation:'I can'},{word:'no puedo',translation:'I cannot'},{word:'ayudar',translation:'to help'}] },
    { unit:5, code:'PA1.NED.RES.01', title:'Accept or refuse an offer', canDo:'Accept or politely refuse a familiar offer according to the situation.', domain:'NEEDS', patterns:['Sí, gracias.','No, gracias.','Vale.'], examples:['Sí, gracias.','No, gracias.'], prerequisites:['PA1.SOC.COU.01'], vocabulary:[{word:'sí',translation:'yes'},{word:'no',translation:'no'},{word:'gracias',translation:'thank you'}] },
    { unit:6, code:'PA1.SRV.CLK.01', title:'Use a supported whole hour', canDo:'Ask, understand, or state a supported whole-hour time.', domain:'SURVIVAL', patterns:['¿Qué hora es?','Es la una.','Son las + hora.','A las + hora.'], examples:['¿Qué hora es?','Es la una.','Son las tres.','A las nueve.'], prerequisites:['PA1.SRV.NUM.01'], vocabulary:[{word:'hora',translation:'hour / time'},{word:'a las',translation:'at (time)'}] },
    { unit:6, code:'PA1.SRV.DIR.01', title:'Follow a short supported route', canDo:'Follow or give one turn, with two familiar steps as an extension.', domain:'SURVIVAL', patterns:['A la derecha.','A la izquierda.','Todo recto.'], examples:['A la derecha.','Todo recto y a la izquierda.'], prerequisites:['PA1.SRV.LOC.02'], vocabulary:[{word:'derecha',translation:'right'},{word:'izquierda',translation:'left'},{word:'todo recto',translation:'straight ahead'}] },
    { unit:7, code:'PA1.INT.QST.01', title:'Ask for a missing detail', canDo:'Choose a taught question for the detail missing from an interaction.', domain:'INTERACTION', patterns:['¿Qué?','¿Quién?','¿Dónde?','¿Cuándo?','¿Cuánto?'], examples:['¿Dónde?','¿Cuándo?','¿Cuánto cuesta?'], prerequisites:[], vocabulary:[{word:'quién',translation:'who'},{word:'dónde',translation:'where'},{word:'cuándo',translation:'when'},{word:'cuánto',translation:'how much'}] },
    { unit:7, code:'PA1.INT.WRD.01', title:'Ask how to express an unknown word', canDo:'Ask how to say an unknown word and request a moment when needed.', domain:'INTERACTION', patterns:['¿Cómo se dice + palabra?','No sé.','Un momento, por favor.'], examples:['¿Cómo se dice “water”?','No sé. Un momento, por favor.'], prerequisites:['PA1.INT.UND.01'], vocabulary:[{word:'cómo se dice',translation:'how do you say'},{word:'no sé',translation:'I do not know'},{word:'un momento',translation:'one moment'}] },
] as const
