'use client'

/**
 * NextActionCard — the dominant dashboard card.
 * Generated by the adaptive engine, never hardcoded; the WHY line
 * makes the adaptation transparent (Art. 20).
 */
import Link from 'next/link'
import { ArrowRight, Lightbulb } from 'lucide-react'
import type { NextAction } from '@/lib/summary'

export default function NextActionCard({ action }: { action: NextAction }) {
    return (
        <div className="relative h-full overflow-hidden rounded-2xl border border-glow/30 bg-gradient-to-br from-amber-950/50 via-[#13131B] to-[#13131B] p-6">
            <p className="mb-2 text-[11px] uppercase tracking-widest text-glow">Your next mission</p>
            <h2 className="font-display mb-1 text-2xl font-bold text-cream">{action.title}</h2>
            <p className="mb-3 text-sm text-cream/70">{action.canDo}</p>
            <p className="mb-5 flex items-center gap-1.5 text-xs text-cream/50">
                <Lightbulb className="h-3.5 w-3.5 text-glow" /> {action.reason}
            </p>
            <Link
                href={action.href}
                className="inline-flex items-center gap-2 rounded-xl bg-glow px-5 py-3 text-sm font-bold text-night-900 transition-colors hover:bg-glow-bright"
            >
                {action.kind === 'gateway' ? 'Prove it' : 'Enter the scene'} <ArrowRight className="h-4 w-4" />
            </Link>
        </div>
    )
}
